### ISSUE TITLE
npm installs outdated version

### ISSUE THREAD

**Issue by hashchange** [karma-runner/karma-slimerjs-launcher#11]
Unfortunately, `npm install karma-slimerjs-launcher` does not install the latest version, and the fixes in #10 don't make it to disk.

@aymericbeaumet This should be easy to fix. My guess is that the version in package.json needs to be changed to 0.1.3, then npm publish.

Cheers! Michael

**Comment by aymericbeaumet** [comment]
We use an automated process to deploy the karma-related packages. It seems it doesn't handle karma-slimerjs-launcher yet (it took some time to transfer the NPM rights).

I'll look into it.

**Comment by mickeyvip** [comment]
+1

**Comment by aymericbeaumet** [comment]
I contacted @vojtajina, waiting for him to configure the automated process so as to also deploy this plugin. If you guys really need the latest version, install it using the repository git address by now.

**Comment by RevanProdigalKnight** [comment]
It's the beginning of October and this still hasn't been fixed. I need to have a browser to run on a Jenkins server that understands ES6 and so far as I can tell this is the only one that I can install into my project's node_modules directory for versioning purposes.

**Comment by aymericbeaumet** [comment]
@maksimr @zzo @Dignifiedquire: what's the new deployment process? can we make sure to include this repository

**Comment by Dignifiedquire** [comment]
@aymericbeaumet all manual right now I'm afraid, I'll cut a new release later today

**Comment by aymericbeaumet** [comment]
@Dignifiedquire: thanks!

**Comment by Dignifiedquire** [comment]
Published `0.2.0`

**Comment by aymericbeaumet** [comment]
Thanks @Dignifiedquire :+1:
